version: "3.7"

services:

  webapp:
    build:
      context: .
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - sensor_data_volume:/var/lib/mysql

  migration:
    image: device-integration_nokia_webapp:latest
    command: ["./wait-for-it.sh", "--timeout=0", "device-integration_nokia_mysql_1:3306", "--", "npm", "run", "migrate"]
    depends_on:
      - mysql
    links:
      - mysql

  proxy:
    build:
      context: ./proxy
    tty: true
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - webapp
    links:
      - webapp

volumes:
  sensor_data_volume:

networks:
  default:
    external:
      name: device_network
